package com.infy.ceh.management.autonomics.tasks.impl; 

import com.infy.ceh.management.ems.dto.IPPIssue;
import com.infy.ceh.management.ems.dto.IPPIncident;
import com.infy.ceh.management.ems.dto.IncidentCreationRequestDto;
import java.util.List;
import java.util.Arrays;
import java.util.Map;

function void setupIncident(IncidentCreationRequestDto req, String impact, String urgency) {
    Map postMap = req.getPostMap();
    postMap.put("category", "Infrastructure");
    postMap.put("subcategory", "Other");
    postMap.put("u_x_business_model", "corporate");
    postMap.put("u_region", "EU");
    postMap.put("impact", impact);
    postMap.put("urgency", urgency);
    postMap.put("assignment_group", getAssignmentGroup(req.getIssue().getName()));
    postMap.put("short_description", req.getIssue().getName());
    postMap.put("description", req.getIssue().getDescription());
    postMap.put("cmdb_ci", req.getIssue().getIssueResources().get(0).getResourceName());
}

function java.lang.String getAssignmentGroup(String name) {
    if (name == null) return "ISM - EOC Monitoring";
    
	String groupName = "";
	
	if(name.contains("MAO Order Management")){
		groupName = "Asia WMS";
	}else if((name.contains("Netskope") || name.contains("NetSkope")) && (name.contains("Publisher") || name.contains("IPSEC Tunnel") || name.contains("GRE Tunnel"))){
		groupName = "ISM - Network";
	}else if(name.contains("Netskope") || name.contains("NetSkope")){
		groupName = "ISM - Security Netskope";
	}else{
		groupName = "ISM - EOC Monitoring";
	}
    return groupName;
}

rule "IncCreationLogicMonitor_1:"
when
    $incidentRequest : IncidentCreationRequestDto(  
		issue.source == "4" 
		&& issue.severity == "CRITICAL" 
		&& issue.name not contains "vSphere Distributed Switch"
	)
then
	setupIncident($incidentRequest, "2", "2");
end

rule "IncCreationLogicMonitor_2:"
when
    $incidentRequest : IncidentCreationRequestDto(  
		issue.source == "4" 
		&& issue.severity == "CRITICAL" 
		&& issue.name contains "Oracle TableSpace Usage"
	)
then
	setupIncident($incidentRequest, "3", "2");
end

rule "IncCreationLogicMonitor_3:"
when
    $incidentRequest : IncidentCreationRequestDto(  
		issue.source == "4" 
		&& issue.severity == "CRITICAL" 
		&& issue.name contains "Oracle Connection Status"
	)
then
	setupIncident($incidentRequest, "2", "1");
end

rule "IncCreationLogicMonitor_4:"
when
    $incidentRequest : IncidentCreationRequestDto(  
		issue.source == "4" 
		&&  issue.severity=="MAJOR" 
		&& issue.name not contains "vSphere Distributed Switch"
		&& issue.name not contains "Oracle Connection Status"
		&& issue.name not contains "Oracle TableSpace Usage"
	)
then
	setupIncident($incidentRequest, "2", "2");
end

rule "IncCreationLogicMonitor_5:"
when
    $incidentRequest : IncidentCreationRequestDto( 
		issue.source == "4" 
		&& issue.severity == "WARN" 
		&& issue.name not matches ".*(PacketsDroppedRx|PacketsReceivedDiscarded|Ping average|Ping sentpkts|OutDiscardPercent|DNS status|CPUBusyPercent|CPU Cores|Host CPU usage State|SystemHealth|VMware vSphere Datastore Status|VMware vSphere ESXi Host Status|DiskReadLatency|VMware vSphere Datastore Capacity|vSphere Distributed Switch|Oracle Connection Status|Oracle TableSpace Usage).*"
	)
then
	setupIncident($incidentRequest, "2", "3");
end

rule "IncCreationLogicMonitor_6:"
when
    $incidentRequest : IncidentCreationRequestDto(  
		issue.source == "4"
		&& issue.severity == "CRITICAL"
		&& issue.name matches ".*The host.*is down" && issue.description matches "(?s).*Device Type : Logicmonitor Collectors.*"
	)
then
	setupIncident($incidentRequest, "2", "1");
end

rule "IncCreationLogicMonitor_7:"
when
    $incidentRequest : IncidentCreationRequestDto(  
		issue.source == "4" 
		&& (issue.severity == "CRITICAL" || issue.severity == "MAJOR" || issue.severity == "WARN")  
		&& issue.name contains "Veeam Jobs: Backups-"
	)
then
	setupIncident($incidentRequest, "2", "3");
end

rule "IncCreationLogicMonitor_8:"
when
    $incidentRequest : IncidentCreationRequestDto(  
		issue.source == "4" 
		&& (issue.severity == "CRITICAL" || issue.severity == "MAJOR")  
		&& issue.name matches "(?:.*Cohesity_DataPlatform_Alerts.*|.*WMI is not accessible. See error message for likely issue.*|.*Veeam Jobs.*|.*.*Veeam Jobs: Backups-.*Status.*)"
	)
then
	setupIncident($incidentRequest, "2", "3");
end

rule "IncCreationLogicMonitor_9:"
when
    $incidentRequest : IncidentCreationRequestDto(  
		issue.source == "4" 
		&& (issue.severity == "CRITICAL" || issue.severity == "MAJOR")  
		&& issue.name matches "(?:.*Volume Capacity.*PercentUsed.*|.*MemoryUtilizationPercent.*|.*CPUBusyPercent.*)"
	)
then
	List<String> deviceNamesList=Arrays.asList("BWOBODSP1","BWOBOLUMP1","BWOBOP01","BWOBOP02","BWOBOWBP01","BWOBOWBP02");
	
	String impact = "2";
	String urgency = "3";

	if(deviceNamesList.contains($incidentRequest.getIssue().getIssueResources().get(0).getResourceName())){
		impact = "1";
		urgency = "2";
	}
	setupIncident($incidentRequest, impact, urgency);
end